# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: local
  hooks:
  - id: check-poetry
    name: Poetry check
    description: Validates the structure of the pyproject.toml file
    entry: poetry check
    language: system
    pass_filenames: false
    files: pyproject.toml
  - id: pytest
    name: Check pytest unit tests pass
    entry: poetry run pytest
    pass_filenames: false
    language: system
    types: [python]
- repo: https://github.com/akaihola/darker
  rev: github-action-v1.3.2-2
  hooks:
  - id: darker
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
